# Config version. To check the latest version, check out https://github.com/rogueliver/playertag
config-version: 2

# The format of the ping in chat.
# You can use MiniMessage tags (e.g. <red>, <bold>, <gradient:red:blue>)
# or Legacy color codes (e.g. &c, &l).
# Placeholder: <name> will be replaced with the mentioned player's name.
ping-format: "<gradient:aqua:blue>@<name></gradient>"

# If true, players can be tagged just by typing their name (e.g. "Hey Herobrine").
# If false, they must use the @ symbol (e.g. "Hey @Herobrine").
tag-without-at: true

# Sound settings
sound:
  enabled: true
  type: "block.note_block.pling"
  volume: 1.0
  pitch: 2.0
